### ISSUE TITLE
User Experience Improves 

### ISSUE THREAD

**Issue by simanglam** [CCU-Class/FrontEnd#4]
Hi,

在現有的鳳梨課表中，如果需要使用刪除功能，需要先將 courseCard 翻面過來再按後面的刪除鍵。刪除作為常用功能，如果可以減少刪除所需的步驟會不會比較好？例如在正面放上一個叉叉 Icon 並在點擊時就可以把 courseCard 刪除，這樣就不用翻過來再把課程刪除了，原本刪除所在的位置也可以留給更多資訊，讓學生可以直接在同網頁中查看詳細的課程訊息，如大綱、評論等。

以下是我嘗試的 Demo

https://github.com/simanglam/PineappleSchedule/tree/dev_dev

我除了在 courseCard 上加入叉叉 icon 外，我還參考 notify 把原本刪除的位置改成更多資訊，點按後彈出視窗顯示更多資訊。

Happy Hacking
Si manglam

**Comment by as6325400** [comment]
你好，很意外，也非常開心居然有人願意看我們的code，非常感謝
但抱歉我們應該不會採用這個方法，主要原因有兩個

1. 我們認為讓課程卡片翻面有一個避免使用者誤觸刪除的作用在
2. 因為目前的下載圖片為獲取整個課表上的Dom的渲染畫面並下載，因此那個 x 會在畫面上出現，會有些影響美觀

因此討論後目前並不打算將這個改變放到網站上，非常抱歉!

另外，關於顯示更多資訊那邊，我們在dev_split那個branch裡有實作一種方式，雖然有一些bug在，但應該能稍微看一下畫面呈現的方式。

可以在左上角的橘色小搜尋框打開後，課程評價點開後看到。非常感謝你做的這些，謝謝!

**Comment by as6325400** [comment]
> Hi,
> 
> 在現有的鳳梨課表中，如果需要使用刪除功能，需要先將 courseCard 翻面過來再按後面的刪除鍵。刪除作為常用功能，如果可以減少刪除所需的步驟會不會比較好？例如在正面放上一個叉叉 Icon 並在點擊時就可以把 courseCard 刪除，這樣就不用翻過來再把課程刪除了，原本刪除所在的位置也可以留給更多資訊，讓學生可以直接在同網頁中查看詳細的課程訊息，如大綱、評論等。
> 
> 以下是我嘗試的 Demo
> 
> https://github.com/simanglam/PineappleSchedule/tree/dev_dev
> 
> 我除了在 courseCard 上加入叉叉 icon 外，我還參考 notify 把原本刪除的位置改成更多資訊，點按後彈出視窗顯示更多資訊。
> 
> Happy Hacking Si manglam
你好，很意外，也非常開心居然有人願意看我們的code，非常感謝
但抱歉我們應該不會採用這個方法，主要原因有兩個

我們認為讓課程卡片翻面有一個避免使用者誤觸刪除的作用在
因為目前的下載圖片為獲取整個課表上的Dom的渲染畫面並下載，因此那個 x 會在畫面上出現，會有些影響美觀
因此討論後目前並不打算將這個改變放到網站上，非常抱歉!

另外，關於顯示更多資訊那邊，我們在dev_split那個branch裡有實作一種方式，雖然有一些bug在，但應該能稍微看一下畫面呈現的方式。

可以在左上角的橘色小搜尋框打開後，課程評價點開後看到。非常感謝你做的這些，謝謝!

**Comment by simanglam** [comment]
Hi,

好的，我能夠了解你們的顧慮。謝謝你們願意花時間做這件事情，不論是花時間回覆我的 Issues 或做這個選課系統，這都是一件很偉大的事情，祝你們能夠在這條路上走得更遠。

Happy Hacking
Si manglam
